# ===================================================================
# CONFIGURACIÓN GENERAL DE LA APLICACIÓN
# ===================================================================
spring.application.name=SistemaPagosArenales
server.servlet.context-path=/sistemapagoarenales

# URL por defecto y ordenamiento de Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# ===================================================================
# CONEXIÓN A BASE DE DATOS (SUPABASE POSTGRESQL - SESSION POOLER)
# ===================================================================
spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.qbqxrgvfdkvgsyuwkekj
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# ===================================================================
# SERVICIO DE CORREO (GMAIL SMTP)
# ===================================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=brunosebastianflores@gmail.com
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# ===================================================================
# APIS EXTERNAS Y CREDENCIALES DE TERCEROS
# ===================================================================
# Token de apis.net.pe para consultas de DNI (Cuenta de Christian)
reniec.api.token=Bearer sk_15635.w8QLdrkS8r8VBE5gml2TpLtjY9l9MbwL

# Configuración de Almacenamiento Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:shattg2o}
cloudinary.api-key=${CLOUDINARY_API_KEY:547784328483962}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:TbD3kO0evKE74s1PXiazwzsN0Zg}