# ===================================================================
# CONEXIÓN A BASE DE DATOS LOCAL - SQL SERVER
# ===================================================================
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=CC_Arenales;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=@123remo123@
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / HIBERNATE PARA SQL SERVER
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect