# NOMBRE DE LA APLICACION
spring.application.name=SistemaPagosArenales

# URL DEL PROYECTO
server.servlet.context-path=/sistemapagoarenales

# CONEXION A SQL SERVER
spring.datasource.url=jdbc:sqlserver://localhost;instanceName=SQLEXPRESS;databaseName=CC_Arenales;encrypt=false;trustServerCertificate=true

# USUARIO SQL SERVER
spring.datasource.username=
spring.datasource.password=

# DRIVER
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Mantener nombres exactos de columnas/tablas
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl