#NOMBRE DE LA APLICACION
spring.application.name=SistemaPagosArenales

# conectando a sql server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=CC_Arenales;encrypt=true;trustServerCertificate=true

#URL DEL PROYECTO
server.servlet.context-path=/sistemapagoarenales

#USUARIO DE LA BD
#spring.datasource.username=sa_cca
spring.datasource.username=sa

#CLAVE DE LA BD
#spring.datasource.password=Hollowmeow_
spring.datasource.password=@123remo123@

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect